### ISSUE TITLE
Exception thrown when program tries to change proxy

### ISSUE THREAD

**Issue by Lazora** [EquityMiner/equity_cracker-v3#6]
Changing proxy..
Exception - miner
equity_cracker.MyException: Maximal checks reached
   at equity_cracker.Program.<>c__DisplayClass11_0.<<Main>b__0>d.MoveNext() in C:\Users\XgV12u3\source\repos\equity_cracker\Program.cs:line 255

**Comment by Lazora** [comment]
and I don't think it's changing the proxy, it's using the same proxy and it gives me `Failed getting balance | Status code: 429` error for a couple of minutes (I already changed the config)

**Comment by 4telly** [comment]
@Lazora Known error, wait for next release
